healer:
 id: 0
 behaviors:
  - name: HealBehavior
    priority: 1
 applicableCommands:
  - name: HealCommand
    commanders: [healer]
	
damager:
 id: 1
 behaviors:
  - name: HitBehavior
    priority: 2
 applicableCommands:
  - name: HealCommand
    commanders: [healer]
  - name: HitCommand
    commanders: [enemy]
	
enemy:
 id: 2
 behaviors:
  - name: HitBehavior
    priority: 2
 applicableCommands:
  - name: HitBehavior
    commanders: [damager]